services:
  nginx:
    depends_on:
      - site-a
      - site-b
      - site-c

  site-a:
    image: nginx:alpine
    volumes:
      - ./sites/site-a:/usr/share/nginx/html:ro

  site-b:
    image: nginx:alpine
    volumes:
      - ./sites/site-b:/usr/share/nginx/html:ro

  site-c:
    image: nginx:alpine
    volumes:
      - ./sites/site-c:/usr/share/nginx/html:ro
